---
title: "BoletinTema1chulde"
author: "Lucia Chulvi Deogracia"
date: "2023-02-15"
output: html_document
---

```{r}
#cargamos la libreria de mammals
library(MASS)
A<-MASS::mammals


dim(A)
head(A)
tail(A)
str(A)
rownames(A)
colnames(A)

#Vemos que contiene Animals2
B<-Animals2


 
dim(B)
head(B)
tail(B)
str(B)
rownames(B)
colnames(B)


#d)
(commonAmbos<-intersect(rownames(A),rownames(B)))

#e)
AnoB<-setdiff(rownames(A),rownames(B))

AnoB

BnoA<-setdiff(rownames(B),rownames(A))

BnoA

```

Ejercicio 2

```{r}
library(MASS) 
  library(car)
library(robustbase) 
car::qqPlot(log(mammals$brain))

qqPlot(log(Animals2$brain))
```

Ejercicio3:

```{r}
rm(list = ls()) 
libReturn<-library() 
libReturn[[2]][1:5,1]

head(libReturn$results,n=5)
```

Ejercicio4:

```{r}
dim(cabbages)
str(cabbages)
head(cabbages)
tail(cabbages)
summary(cabbages)
any(is.na(cabbages))
colSums(sapply(cabbages,  is.na))
```

Ejercicio6:

```{r}
ggplot(data=cabbages, aes(x=VitC,  fill=Cult))+geom_histogram(alpha=0.5)
```

Ejercicio7:

```{r}
#Diagrama de dispersión global.
plot(whiteside$Temp, whiteside$Gas)

#Diagrama de dispersión etiquetando según un factor.
plot(whiteside$Temp,  whiteside$Gas,  pch=c(6,16)[whiteside$Insul]) 
legend(x="topright",legend=c("Insul  =  Before","Insul  =  After"),  pch=c(6,16)) # Planteamos 2 modelos lineales, uno para los datos de cada factor
Model1 <- lm(Gas ~ Temp, data = whiteside, subset = which(Insul == "Before")) 
Model2 <- lm(Gas ~ Temp, data = whiteside, subset = which(Insul == "After")) 
# Representamos las rectas  correspondientes  a  cada  modelo  lineal 
abline(Model1, lty=2)

abline(Model2)

```
